export default {
  products: [
    {
      _id: '1',
      name: 'shirt',
      category: 'Shirts',
      image: '/images/product-6.jpg',
      price: 59,
      brand: 'shirt brand',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'shirt',
      category: 'Shirts',
      image: '/images/product-6.jpg',
      price: 59,
      brand: 'shirt brand',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'shirt',
      category: 'Shirts',
      image: '/images/product-6.jpg',
      price: 59,
      brand: 'shirt brand',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '4',
      name: 'shirt',
      category: 'Shirts',
      image: '/images/product-6.jpg',
      price: 59,
      brand: 'shirt brand',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'shirt',
      category: 'Shirts',
      image: '/images/product-6.jpg',
      price: 59,
      brand: 'shirt brand',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'shirt',
      category: 'Shirts',
      image: '/images/product-6.jpg',
      price: 59,
      brand: 'shirt brand',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
